from __future__ import annotations

import csv
from pathlib import Path
from collections.abc import Callable, Iterable

from rosbagel.core.manifest import sanitize_topic_name
from rosbagel.core.models import ExportResult
from rosbagel.core.point_cloud import (
    expanded_point_field_names,
    expanded_point_row,
    iter_point_cloud_rows,
    point_cloud_field_specs,
    point_cloud_point_count,
    point_field_pcd_size,
    point_field_pcd_type,
    point_field_ply_type,
)
from rosbagel.core.progress import ProgressCallback, advance_progress


def export_topic_point_clouds(
    reader: object,
    topic: str,
    out_dir: str | Path,
    *,
    point_format: str,
    bag_start_timestamp_ns: int | None = None,
    progress_callback: ProgressCallback | None = None,
) -> ExportResult:
    fmt = point_format.lower()
    if fmt not in {"pcd", "ply"}:
        raise ValueError(f"Unsupported point cloud export format: {point_format}")

    output_dir = Path(out_dir) / "pointclouds" / sanitize_topic_name(topic)
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamps_path = output_dir / "timestamps.csv"
    warnings: list[str] = []
    source_count = 0
    cloud_count = 0
    first_timestamp: int | None = None
    last_timestamp: int | None = None

    with timestamps_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "frame_index",
                "timestamp_ns",
                "timestamp_sec_from_start",
                "filename",
                "point_count",
                "field_names",
            ],
        )
        writer.writeheader()
        for record in reader.iter_messages(topics=[topic]):
            source_count += 1
            first_timestamp = record.timestamp_ns if first_timestamp is None else first_timestamp
            last_timestamp = record.timestamp_ns
            if record.decoded is None:
                warnings.append(f"Skipped message at {record.timestamp_ns}: message was not decoded")
                advance_progress(progress_callback)
                continue
            if record.msgtype != "sensor_msgs/msg/PointCloud2":
                warnings.append(
                    f"Skipped message at {record.timestamp_ns}: {record.msgtype} is not PointCloud2"
                )
                advance_progress(progress_callback)
                continue

            filename = f"{cloud_count:06d}.{fmt}"
            output_path = output_dir / filename
            field_names = expanded_point_field_names(record.decoded)
            if not {"x", "y", "z"}.issubset(set(field_names)):
                warnings.append(
                    f"Point cloud at {record.timestamp_ns} does not contain all x/y/z fields."
                )
            if fmt == "pcd":
                point_count = _write_pcd(record.decoded, output_path)
            else:
                point_count = _write_ply(record.decoded, output_path)
            writer.writerow(
                {
                    "frame_index": cloud_count,
                    "timestamp_ns": record.timestamp_ns,
                    "timestamp_sec_from_start": _sec_from_start(
                        record.timestamp_ns, bag_start_timestamp_ns
                    ),
                    "filename": filename,
                    "point_count": point_count,
                    "field_names": " ".join(field_names),
                }
            )
            cloud_count += 1
            advance_progress(progress_callback)

    if source_count and cloud_count != source_count:
        warnings.append(f"Exported {cloud_count} point clouds from {source_count} source messages.")

    return ExportResult(
        topic=topic,
        format=fmt,
        output_path=str(output_dir),
        message_count=cloud_count,
        first_timestamp_ns=first_timestamp,
        last_timestamp_ns=last_timestamp,
        warnings=sorted(set(warnings)),
    )


def _write_pcd(message: object, output_path: Path) -> int:
    specs = point_cloud_field_specs(message)
    point_count = _count_rows(message)
    names = expanded_point_field_names(message)
    sizes = _expanded_values(specs, lambda spec: str(point_field_pcd_size(spec)))
    types = _expanded_values(specs, point_field_pcd_type)
    counts = ["1"] * len(names)

    with output_path.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("# .PCD v0.7 - Point Cloud Data file generated by rosbagel\n")
        handle.write("VERSION 0.7\n")
        handle.write(f"FIELDS {' '.join(names)}\n")
        handle.write(f"SIZE {' '.join(sizes)}\n")
        handle.write(f"TYPE {' '.join(types)}\n")
        handle.write(f"COUNT {' '.join(counts)}\n")
        handle.write(f"WIDTH {point_count}\n")
        handle.write("HEIGHT 1\n")
        handle.write("VIEWPOINT 0 0 0 1 0 0 0\n")
        handle.write(f"POINTS {point_count}\n")
        handle.write("DATA ascii\n")
        for row in iter_point_cloud_rows(message):
            handle.write(" ".join(_format_value(value) for value in expanded_point_row(message, row)))
            handle.write("\n")
    return point_count


def _write_ply(message: object, output_path: Path) -> int:
    specs = point_cloud_field_specs(message)
    point_count = _count_rows(message)
    field_names = expanded_point_field_names(message)
    ply_types = _expanded_values(specs, point_field_ply_type)

    with output_path.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("ply\n")
        handle.write("format ascii 1.0\n")
        handle.write("comment Generated by rosbagel\n")
        handle.write(f"element vertex {point_count}\n")
        for field_type, field_name in zip(ply_types, field_names):
            handle.write(f"property {field_type} {field_name}\n")
        handle.write("end_header\n")
        for row in iter_point_cloud_rows(message):
            handle.write(" ".join(_format_value(value) for value in expanded_point_row(message, row)))
            handle.write("\n")
    return point_count


def _expanded_values(specs: Iterable[object], value_for_spec: Callable[[object], object]) -> list[str]:
    values: list[str] = []
    for spec in specs:
        value = str(value_for_spec(spec))
        count = int(getattr(spec, "count", 1) or 1)
        values.extend(value for _ in range(count))
    return values


def _count_rows(message: object) -> int:
    return point_cloud_point_count(message)


def _format_value(value: object) -> str:
    if isinstance(value, float):
        return format(value, ".9g")
    return str(value)


def _sec_from_start(timestamp_ns: int, bag_start_timestamp_ns: int | None) -> float | None:
    if bag_start_timestamp_ns is None:
        return None
    return (timestamp_ns - bag_start_timestamp_ns) / 1e9
